site_name: Compose Mind Mapper
site_description: 'Jetpack Compose Mind Mapping Library'
site_author: 'Waqas Tahir'
site_url: 'https://codeckle.github.io/compose-mapper/'
remote_branch: gh-pages

docs_dir: docs

repo_name: 'compose-mapper'
repo_url: 'https://github.com/codeckle/compose-mapper'

theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - 'Overview': README.md
  - 'API' : api/mapper